repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1  # Use the latest version from https://github.com/astral-sh/ruff-pre-commit/releases
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format