name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'  # Specify your Node.js version

      - name: Install dependencies
        run: |
          cd frontend  # Change to your frontend directory
          npm install

      - name: Run tests
        run: |
          cd frontend  # Change to your frontend directory
          npm test
