name: Frontend Tests

on:
  push:
    branches:
      - feature-component-validations
  pull_request:
    branches:
      - feature-component-validations

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (make sure to use the correct Node.js version for your project)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install --force

      # Step 4: Run tests
      - name: Run frontend tests
        run: npm test -- --watchAll=false
